### ISSUE TITLE
Cannot find module 'csv'

### ISSUE THREAD

**Issue by timster83** [scottwestover/LE-realtime-db-example#1]
I have encountered errors when running this application on both Ubuntu and Windows 7 environments. After 'npm install' and 'npm start', the application advises that the 'csv' module was not found (it does not appear to be a requirement in the package.json). 

After installing 'csv' manually via npm, the application starts as expected.

**Comment by scottwestover** [comment]
Thank you for opening this issue. The 'csv' module was not included in the package.json file. I have uploaded a newer version of the dashboard, and this issue should now be fixed.
